### ISSUE TITLE
Proxmox Virtual Environment service 

### ISSUE THREAD

**Issue by EWANZO101** [Veloxbill/tracker#16]
### Describe the solution you'd like

Enhance this service by allowing the addition of multiple Proxmox links. Instead of relying on a single Proxmox cluster, it would be safer to have the ability to add more than one URLs to the panel

**Comment by devdamo** [comment]
Our system will allow people to add multiple instances. More info will be addressed soon.

**Comment by SiFuMax09** [comment]
Duplicate of #2
